#!/bin/bash -eu

python_version=$(python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")

scripts_dir=$(dirname $0)
examples_dir=$(realpath ${scripts_dir}/../examples)

# Run from a different working directory to make sure the Python code
# is picked up via its package and not from the local path.
cd /tmp

set -x

uv run ${examples_dir}/example.py --foo foo

uv run ${examples_dir}/example_choices.py --mode a

uv run ${examples_dir}/example_sub_commands.py foo file
uv run ${examples_dir}/example_sub_commands.py bar --src src --dst dst
